language: java
jdk:
  - openjdk11
sudo: required
services:
  - docker
addons:
  sonarcloud:
    organization: "lukaszrys"
    token:
      secure: $SONAR_TOKEN

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=lukaszrys_efficient-spending
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./mvnw deploy -P deploy-docker; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)