language: java
jdk:
  - openjdk11
sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

script:
#  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./mvnw deploy -P deploy-docker; fi
  - ./mvnw deploy -P deploy-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)