spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authorization-service-db
      username: authorization
      password: authorization
server:
  servlet:
    context-path: /auth
  port: 8030