amqp:
  queues:
    accountService: create_account
spring:
  data:
    mongodb:
      host: localhost
      port: 27031
      database: authorization-service-db
      username: authorization
      password: authorization
  rabbitmq:
    host: localhost
    port: 5682
    username: guest
    password: guest
server:
  servlet:
    context-path: /auth
  port: 8030