version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5682:5672'
      - '15672:15672'
    networks:
      - efficient-network
  mongo-account:
    image: mongo
    restart: always
    ports:
      - "27030:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: account-service-db
    volumes:
      - ./mongo-account-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - efficient-network
  mongo-authorization:
    image: mongo
    restart: always
    ports:
      - "27031:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: authorization-service-db
    volumes:
      - ./mongo-authorization-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - efficient-network

networks:
  efficient-network: